### ISSUE TITLE
Evaluation Code

### ISSUE THREAD

**Issue by yanlong1211** [Bat-Reality/DDRCU#1]
Dear Author
There seems to be no evaluation model related code in the code you provided, will you provide evaluation related code at a later stage?
Thank you very much for taking the time to read my issue.l look forward to your response and hope to have the opportunity to learn more from your work.

**Comment by Bat-Reality** [comment]
Please run the `RUN/infer_strat.sh` file to obtain the evaluation results.

**Comment by yanlong1211** [comment]
Thank you, your answers are very helpful, good luck with your work!
