### ISSUE TITLE
configuration environment file and training time

### ISSUE THREAD

**Issue by yanlong1211** [Bat-Reality/DDRCU#2]
Dear Author
  I don't see the corresponding experiment-specific environment profile in the code configuration file. Will you update the configuration environment file later? Also, I would like to know the total training time of the model as well as the dataset file DATA. This information is crucial for me to rationalize my resource allocation and estimate the time required for the experiment.
  
  I look forward to your response and hope to have the opportunity to learn more from your work.

**Comment by Bat-Reality** [comment]
I will organize and publish the configuration files. 

The main model can be trained on a 3090 GPU for 8 hours.

**Comment by Bat-Reality** [comment]
> Dear Author I don't see the corresponding experiment-specific environment profile in the code configuration file. Will you update the configuration environment file later? Also, I would like to know the total training time of the model as well as the dataset file DATA. This information is crucial for me to rationalize my resource allocation and estimate the time required for the experiment.
> 
> I look forward to your response and hope to have the opportunity to learn more from your work.

I have uploaded the complete configuration file.

**Comment by lionel157** [comment]
Have you successfully reproduced this project?
