### ISSUE TITLE
train.txt

### ISSUE THREAD

**Issue by lionel157** [Bat-Reality/DDRCU#4]
Dear Author

I hope this message finds you well.

   I have been exploring the project and encountered a small issue. The documentation mentions a train.txt file in pre_peocess.py, but I couldn’t locate it in the repository. I was wondering if you could kindly clarify the following:
1. Is the train.txt file something we need to generate ourselves?
2. If so, could you provide an example or details about its required format?
3. If it is included in the project, could you guide me on where to find it?
Thank you very much for your time and assistance. I greatly appreciate your help and look forward to your response.

**Comment by Bat-Reality** [comment]
You can refer to the code in https://github.com/thu-coai/Emotional-Support-Conversation/blob/main/codes_zcj/_reformat/process.py to divide the data set in ESConv to get train.txt.

**Comment by lionel157** [comment]
> You can refer to the code in https://github.com/thu-coai/Emotional-Support-Conversation/blob/main/codes_zcj/_reformat/process.py to divide the data set in ESConv to get train.txt.

Thank you for your answer, it has been very helpful to me
